"""empty message

Revision ID: 926c3957654b
Revises: f801b91fadca
Create Date: 2019-12-15 22:26:08.741386

"""

# revision identifiers, used by Alembic.
revision = '926c3957654b'
down_revision = 'f801b91fadca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('created_on', sa.Float(), nullable=True))
    op.add_column('employee_info', sa.Column('mobile_number', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_info', 'mobile_number')
    op.drop_column('employee_info', 'created_on')
    ### end Alembic commands ###
