"""empty message

Revision ID: b609960e7d65
Revises: e4ce034096c7
Create Date: 2019-12-15 22:27:08.995847

"""

# revision identifiers, used by Alembic.
revision = 'b609960e7d65'
down_revision = 'e4ce034096c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'employee_info', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_info', type_='unique')
    op.drop_column('employee_info', 'email')
    ### end Alembic commands ###
