"""empty message

Revision ID: e4ce034096c7
Revises: 926c3957654b
Create Date: 2019-12-15 22:26:51.567011

"""

# revision identifiers, used by Alembic.
revision = 'e4ce034096c7'
down_revision = '926c3957654b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_info_email_key', 'employee_info', type_='unique')
    op.drop_column('employee_info', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('email', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_unique_constraint('employee_info_email_key', 'employee_info', ['email'])
    ### end Alembic commands ###
