"""empty message

Revision ID: f801b91fadca
Revises: None
Create Date: 2019-12-15 22:25:29.228743

"""

# revision identifiers, used by Alembic.
revision = 'f801b91fadca'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_info', 'created_on')
    op.drop_column('employee_info', 'mobile_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('mobile_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee_info', sa.Column('created_on', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    ### end Alembic commands ###
